# Generated by Django 5.2 on 2025-05-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visitor',
            name='detector_vi_timesta_0e8213_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='detector_vi_ip_addr_127c3a_idx',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(max_length=200),
        ),
    ]
